# setup.yml
---
  - hosts: appserver
    become: yes
    tasks:
    - name: Transfer job file
      copy:
        src: ../files/job.nomad
        dest: $PWD

    - name: Run Nomad job
      command: nomad job run job.nomad